name: Deploy Host App

on:
  push:
    branches: [main]
    paths: [ 'host-app/**' ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: host-app
  ECS_SERVICE: host-app-service
  ECS_CLUSTER: fiap-microfrontend
  REMOTE_ECS_SERVICE: remote-app-service

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::803872155909:role/GitHubActionsECRPushRole
        aws-region: ${{ env.AWS_REGION }}

    - uses: aws-actions/amazon-ecr-login@v2
      id: login-ecr

    - name: Discover Remote App ALB DNS
      run: |
        TG_ARN=$(aws ecs describe-services \
          --cluster $ECS_CLUSTER \
          --services $REMOTE_ECS_SERVICE \
          --query "services[0].loadBalancers[0].targetGroupArn" \
          --output text)

        if [ "$TG_ARN" = "None" ] || [ -z "$TG_ARN" ]; then
          echo "Remote service does not have a Load Balancer"
          exit 1
        fi

        LB_ARN=$(aws elbv2 describe-target-groups \
          --target-group-arns $TG_ARN \
          --query "TargetGroups[0].LoadBalancerArns[0]" \
          --output text)

        DNS=$(aws elbv2 describe-load-balancers \
          --load-balancer-arns $LB_ARN \
          --query "LoadBalancers[0].DNSName" \
          --output text)

        echo "REMOTE_APP_URL=http://$DNS" >> $GITHUB_ENV



    - name: Build & Push
      working-directory: ./host-app
      run: |
        IMAGE=${{ steps.login-ecr.outputs.registry }}/host-app:${{ github.sha }}
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Create log group
      run: |
        aws logs create-log-group \
          --log-group-name /ecs/host-app \
          --region us-east-2 || true

    - name: Render task definition
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: host-app/task-definition.json
        container-name: host-app
        image: ${{ steps.login-ecr.outputs.registry }}/host-app:${{ github.sha }}
        environment-variables: |
          REMOTE_APP_URL=${{ env.REMOTE_APP_URL }}

    - name: Deploy ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        service: host-app-service
        cluster: fiap-microfrontend
        wait-for-service-stability: true

    - name: Force desired count
      run: |
        aws ecs update-service \
          --cluster fiap-microfrontend \
          --service host-app-service \
          --desired-count 1

